apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-k8s-demo
  template:
    metadata:
      labels:
        app: flask-k8s-demo
    spec:
      containers:
        - name: flask-container
          image: flask-k8s-demo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000


